import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "../components/ui/toaster";
axios.baseURL="https://suvidya-chemtech-quiz.vercel.app/"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + " bg-[#04136b]"}>
        <main className="h-screen w-screen p-3">{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
